/* tslint:disable */
/* eslint-disable */
/**
 * full-stack-framework API
 * Automatically generated OpenAPI spec from Postman collection \"full-stack-framework\"
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Category {
    'id'?: number;
    'name'?: string;
    'idle_device'?: number;
    'using_device'?: number;
}
export interface CategoryCreateRequest {
    'name': string;
}
export interface CategoryListResponse {
    'categories'?: Array<Category>;
}
export interface Device {
    'id'?: number;
    'category'?: string;
    'name'?: string;
    'status'?: string;
    'user'?: string;
    'owner'?: string;
    'note'?: string;
}
export interface DeviceCreateRequest {
    'category': string;
    'name': string;
    'owner'?: string;
    'note'?: string;
}
export interface DeviceListResponse {
    'Devices'?: Array<DeviceShort>;
}
export interface DeviceShort {
    'id'?: number;
    'name'?: string;
    'status'?: string;
    'user'?: string;
}
export interface DeviceUserRequest {
    'user': string;
}
export interface LoginRequest {
    'username': string;
    'password': string;
}
export interface LoginResponse {
    'message': string;
    'token': string;
}
export interface MessageResponse {
    'message'?: string;
}

/**
 * AccountApi - axios parameter creator
 */
export const AccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginRequest' is not null or undefined
            assertParamExists('login', 'loginRequest', loginRequest)
            const localVarPath = `/api/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountApi - functional programming interface
 */
export const AccountApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountApi - factory interface
 */
export const AccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountApiFp(configuration)
    return {
        /**
         * 
         * @summary Login
         * @param {LoginRequest} loginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountApi - object-oriented interface
 */
export class AccountApi extends BaseAPI {
    /**
     * 
     * @summary Login
     * @param {LoginRequest} loginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginRequest: LoginRequest, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logout(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CategoryApi - axios parameter creator
 */
export const CategoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create category
         * @param {CategoryCreateRequest} categoryCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCategory: async (categoryCreateRequest: CategoryCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'categoryCreateRequest' is not null or undefined
            assertParamExists('createCategory', 'categoryCreateRequest', categoryCreateRequest)
            const localVarPath = `/api/category`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(categoryCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete category
         * @param {string} name Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCategory: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('deleteCategory', 'name', name)
            const localVarPath = `/api/category/{name}`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get category
         * @param {string} name Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategory: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getCategory', 'name', name)
            const localVarPath = `/api/category/{name}`
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/category`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoryApi - functional programming interface
 */
export const CategoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create category
         * @param {CategoryCreateRequest} categoryCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCategory(categoryCreateRequest: CategoryCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCategory(categoryCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CategoryApi.createCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete category
         * @param {string} name Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCategory(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCategory(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CategoryApi.deleteCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get category
         * @param {string} name Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategory(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Category>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategory(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CategoryApi.getCategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCategories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCategories(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CategoryApi.listCategories']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CategoryApi - factory interface
 */
export const CategoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoryApiFp(configuration)
    return {
        /**
         * 
         * @summary Create category
         * @param {CategoryCreateRequest} categoryCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCategory(categoryCreateRequest: CategoryCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.createCategory(categoryCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete category
         * @param {string} name Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCategory(name: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteCategory(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get category
         * @param {string} name Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategory(name: string, options?: RawAxiosRequestConfig): AxiosPromise<Category> {
            return localVarFp.getCategory(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCategories(options?: RawAxiosRequestConfig): AxiosPromise<CategoryListResponse> {
            return localVarFp.listCategories(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CategoryApi - object-oriented interface
 */
export class CategoryApi extends BaseAPI {
    /**
     * 
     * @summary Create category
     * @param {CategoryCreateRequest} categoryCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCategory(categoryCreateRequest: CategoryCreateRequest, options?: RawAxiosRequestConfig) {
        return CategoryApiFp(this.configuration).createCategory(categoryCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete category
     * @param {string} name Category name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteCategory(name: string, options?: RawAxiosRequestConfig) {
        return CategoryApiFp(this.configuration).deleteCategory(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get category
     * @param {string} name Category name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCategory(name: string, options?: RawAxiosRequestConfig) {
        return CategoryApiFp(this.configuration).getCategory(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCategories(options?: RawAxiosRequestConfig) {
        return CategoryApiFp(this.configuration).listCategories(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DeviceApi - axios parameter creator
 */
export const DeviceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create device
         * @param {DeviceCreateRequest} deviceCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDevice: async (deviceCreateRequest: DeviceCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceCreateRequest' is not null or undefined
            assertParamExists('createDevice', 'deviceCreateRequest', deviceCreateRequest)
            const localVarPath = `/api/device`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDevice: async (category: string, name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'category' is not null or undefined
            assertParamExists('deleteDevice', 'category', category)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('deleteDevice', 'name', name)
            const localVarPath = `/api/device/{category}/{name}`
                .replace('{category}', encodeURIComponent(String(category)))
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevice: async (category: string, name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'category' is not null or undefined
            assertParamExists('getDevice', 'category', category)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('getDevice', 'name', name)
            const localVarPath = `/api/device/{category}/{name}`
                .replace('{category}', encodeURIComponent(String(category)))
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List devices
         * @param {string} category Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices: async (category: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'category' is not null or undefined
            assertParamExists('listDevices', 'category', category)
            const localVarPath = `/api/device/{category}`
                .replace('{category}', encodeURIComponent(String(category)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeviceApi - functional programming interface
 */
export const DeviceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeviceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create device
         * @param {DeviceCreateRequest} deviceCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDevice(deviceCreateRequest: DeviceCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDevice(deviceCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.createDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDevice(category: string, name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDevice(category, name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.deleteDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDevice(category: string, name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Device>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDevice(category, name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.getDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List devices
         * @param {string} category Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDevices(category: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDevices(category, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.listDevices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeviceApi - factory interface
 */
export const DeviceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeviceApiFp(configuration)
    return {
        /**
         * 
         * @summary Create device
         * @param {DeviceCreateRequest} deviceCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDevice(deviceCreateRequest: DeviceCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.createDevice(deviceCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDevice(category: string, name: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
            return localVarFp.deleteDevice(category, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDevice(category: string, name: string, options?: RawAxiosRequestConfig): AxiosPromise<Device> {
            return localVarFp.getDevice(category, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List devices
         * @param {string} category Category name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDevices(category: string, options?: RawAxiosRequestConfig): AxiosPromise<DeviceListResponse> {
            return localVarFp.listDevices(category, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeviceApi - object-oriented interface
 */
export class DeviceApi extends BaseAPI {
    /**
     * 
     * @summary Create device
     * @param {DeviceCreateRequest} deviceCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDevice(deviceCreateRequest: DeviceCreateRequest, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).createDevice(deviceCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete device
     * @param {string} category Category name
     * @param {string} name Device name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDevice(category: string, name: string, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).deleteDevice(category, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get device
     * @param {string} category Category name
     * @param {string} name Device name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDevice(category: string, name: string, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).getDevice(category, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List devices
     * @param {string} category Category name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDevices(category: string, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).listDevices(category, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QrcodeApi - axios parameter creator
 */
export const QrcodeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Borrow device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {DeviceUserRequest} deviceUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        borrowDevice: async (category: string, name: string, deviceUserRequest: DeviceUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'category' is not null or undefined
            assertParamExists('borrowDevice', 'category', category)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('borrowDevice', 'name', name)
            // verify required parameter 'deviceUserRequest' is not null or undefined
            assertParamExists('borrowDevice', 'deviceUserRequest', deviceUserRequest)
            const localVarPath = `/api/qrcode/{category}/{name}`
                .replace('{category}', encodeURIComponent(String(category)))
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {DeviceUserRequest} deviceUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        returnDevice: async (category: string, name: string, deviceUserRequest: DeviceUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'category' is not null or undefined
            assertParamExists('returnDevice', 'category', category)
            // verify required parameter 'name' is not null or undefined
            assertParamExists('returnDevice', 'name', name)
            // verify required parameter 'deviceUserRequest' is not null or undefined
            assertParamExists('returnDevice', 'deviceUserRequest', deviceUserRequest)
            const localVarPath = `/api/qrcode/{category}/{name}`
                .replace('{category}', encodeURIComponent(String(category)))
                .replace('{name}', encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(deviceUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QrcodeApi - functional programming interface
 */
export const QrcodeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QrcodeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Borrow device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {DeviceUserRequest} deviceUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async borrowDevice(category: string, name: string, deviceUserRequest: DeviceUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.borrowDevice(category, name, deviceUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QrcodeApi.borrowDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Return device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {DeviceUserRequest} deviceUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async returnDevice(category: string, name: string, deviceUserRequest: DeviceUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.returnDevice(category, name, deviceUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QrcodeApi.returnDevice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QrcodeApi - factory interface
 */
export const QrcodeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QrcodeApiFp(configuration)
    return {
        /**
         * 
         * @summary Borrow device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {DeviceUserRequest} deviceUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        borrowDevice(category: string, name: string, deviceUserRequest: DeviceUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.borrowDevice(category, name, deviceUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return device
         * @param {string} category Category name
         * @param {string} name Device name
         * @param {DeviceUserRequest} deviceUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        returnDevice(category: string, name: string, deviceUserRequest: DeviceUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.returnDevice(category, name, deviceUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QrcodeApi - object-oriented interface
 */
export class QrcodeApi extends BaseAPI {
    /**
     * 
     * @summary Borrow device
     * @param {string} category Category name
     * @param {string} name Device name
     * @param {DeviceUserRequest} deviceUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public borrowDevice(category: string, name: string, deviceUserRequest: DeviceUserRequest, options?: RawAxiosRequestConfig) {
        return QrcodeApiFp(this.configuration).borrowDevice(category, name, deviceUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return device
     * @param {string} category Category name
     * @param {string} name Device name
     * @param {DeviceUserRequest} deviceUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public returnDevice(category: string, name: string, deviceUserRequest: DeviceUserRequest, options?: RawAxiosRequestConfig) {
        return QrcodeApiFp(this.configuration).returnDevice(category, name, deviceUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



